{{- if .Values.secrets.create }}
{{- $secretName := printf "%s-creds" .Chart.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "litmus-uns.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  POSTGRES_USER: {{ "postgres" | b64enc }}
  {{- $POSTGRES_PASSWORD := (get $secretData "POSTGRES_PASSWORD") | default (randAlphaNum 32 | b64enc) }}
  POSTGRES_PASSWORD: {{ $POSTGRES_PASSWORD | quote }}
  KEYCLOAK_DB: {{ "keycloak" | b64enc }}
  MQTT_DB: {{ "mqtt" | b64enc }}
  MQTT_ADMIN_USER: {{ "mqtt_admin" | b64enc }}
  {{- $MQTT_ADMIN_PASSWORD := (get $secretData "MQTT_ADMIN_PASSWORD") | default (randAlphaNum 32 | b64enc) }}
  MQTT_ADMIN_PASSWORD: {{ $MQTT_ADMIN_PASSWORD | quote }}
  MQTT_SCHEMA: {{ "mqtt" | b64enc }}
  KEYCLOAK_USER: {{ "keycloak" | b64enc }}
  {{- $KEYCLOAK_PASSWORD := (get $secretData "KEYCLOAK_PASSWORD") | default (randAlphaNum 32 | b64enc) }}
  KEYCLOAK_PASSWORD: {{ $KEYCLOAK_PASSWORD | quote }}  
  KEYCLOAK_SCHEMA: {{ "keycloak" | b64enc }}
  KEYCLOAK_ADMIN_USER: {{ "kadmin" | b64enc }}
  {{- $KEYCLOAK_ADMIN_PASSWORD := (get $secretData "KEYCLOAK_ADMIN_PASSWORD") | default (randAlphaNum 16 | b64enc) }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $KEYCLOAK_ADMIN_PASSWORD | quote }}
  {{- $REDIS_PASSWORD := (get $secretData "REDIS_PASSWORD") | default (randAlphaNum 32 | b64enc) }}
  REDIS_PASSWORD: {{ $REDIS_PASSWORD | quote }}    
{{- end }}