apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uns-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: litmus-uns-creds.yaml
    template:
      engineVersion: v2
      data: 
        KEYCLOAK_ADMIN_PASSWORD: "{{ `{{ .keycloakAdminPassword }}` }}"
        KEYCLOAK_ADMIN_USER: "kadmin"
        KEYCLOAK_DB: "keycloak"
        KEYCLOAK_PASSWORD: "{{ `{{ .keycloakPassword }}` }}"
        KEYCLOAK_SCHEMA: "keycloak"
        KEYCLOAK_USER: "keycloak"
        MQTT_ADMIN_PASSWORD: "{{ `{{ .mqttAdminPassword }}` }}"
        MQTT_ADMIN_USER: "mqtt_admin"
        MQTT_DB: "mqtt"
        MQTT_SCHEMA: "mqtt"
        POSTGRES_PASSWORD:  "{{ `{{ .postgresPassword }}` }}"
        POSTGRES_USER: "postgres"
        REDIS_PASSWORD:  "{{ `{{ .redisPassword }}` }}"

        
  data:
  - secretKey: keycloakAdminPassword
    remoteRef:
      key: /litmus-uns-creds
      property: KEYCLOAK_ADMIN_PASSWORD
  - secretKey: keycloakPassword
    remoteRef:
      key: /litmus-uns-creds
      property: KEYCLOAK_PASSWORD
  - secretKey: mqttAdminPassword
    remoteRef:
      key: /litmus-uns-creds
      property: MQTT_ADMIN_PASSWORD   
  - secretKey: postgresPassword
    remoteRef:
      key: /litmus-uns-creds
      property: POSTGRES_PASSWORD   
  - secretKey: redisPassword
    remoteRef:
      key: /litmus-uns-creds
      property: REDIS_PASSWORD   
    