apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace | quote }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uns
      component: keycloak
  template:
    metadata:
      labels:
        app: uns
        component: keycloak
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.keycloak.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.keycloak.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}   
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.keycloak.fsGroup }}
      {{- $creds := printf "%s-creds" .Chart.Name }}
      {{- $postgresHost := include "postgres.host" . }}
      {{- $postgresPort := include "postgres.port" . }}
      containers:
      - name: keycloak
        image: {{ .Values.images.keycloak.name }}:{{ .Values.images.keycloak.tag  | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.images.keycloak.pullPolicy }}
        ports:
        - containerPort: 8080
        securityContext:
          {{- with .Values.keycloak.securityContext }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        resources:
          requests:
            cpu: "{{ .Values.keycloak.resources.requests.cpu }}"
            memory: "{{ .Values.keycloak.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.keycloak.resources.limits.cpu }}"
            memory: "{{ .Values.keycloak.resources.limits.memory }}"
        env:
        - name: "KEYCLOAK_ADMIN"
          valueFrom:
            secretKeyRef:
              name: {{ $creds }}
              key: KEYCLOAK_ADMIN_USER
        - name: "KEYCLOAK_ADMIN_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ $creds }}
              key: "KEYCLOAK_ADMIN_PASSWORD"
        - name: KC_DB_SCHEMA
          valueFrom:
            secretKeyRef:
              name: {{ $creds }}
              key: "KEYCLOAK_SCHEMA"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ $creds }}
              key: KEYCLOAK_USER
        - name: "KC_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ $creds }}
              key: "KEYCLOAK_PASSWORD"
        - name: KC_DB_URL_PORT
          value: {{ $postgresPort | quote }} 
        - name: KC_DB_URL_HOST
          value: {{ $postgresHost | quote }}
        - name: KC_DB_URL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ $creds }}
              key: "KEYCLOAK_DB"
        volumeMounts:
        - name: tmpdir
          subPath: "tmp"
          mountPath: "/tmp"
        - name: tmpdir
          subPath: "data/tmp"
          mountPath: "/opt/keycloak/data/tmp"      
      volumes:
      - name: tmpdir
        emptyDir:
          sizeLimit: "500Mi"
