#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF
CREATE DATABASE ${KEYCLOAK_DB};
CREATE DATABASE ${MQTT_DB};
\c ${MQTT_DB}
CREATE ROLE ${MQTT_ADMIN_USER} LOGIN PASSWORD '${MQTT_ADMIN_PASSWORD}';
CREATE SCHEMA ${MQTT_SCHEMA} AUTHORIZATION ${MQTT_ADMIN_USER};
\c ${KEYCLOAK_DB}
CREATE ROLE ${KEYCLOAK_USER} LOGIN PASSWORD '${KEYCLOAK_PASSWORD}';
CREATE SCHEMA ${KEYCLOAK_SCHEMA} AUTHORIZATION ${KEYCLOAK_USER};
EOF
